version: "3.8"
services:

  test-php:
    image: trafex/php-nginx
    ports:
      - 3000:8080

    volumes:
      - ./index_total.php:/var/www/html/index.php:rw
    networks:
      - inside0
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  inside0:
    external: true
    name: crm_network
  inside:
    external: true 
    name: crm_network1
  outside:
    external: true
    name: ingress-routing
