---
- hosts: all
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        update_cache: true
        name:
           - git
           - htop
           - wget
           - net-tools
           - mc
           - ca-certificates
